[Video-General]
Fullscreen = False
Window Width = 640
Window Height = 480
Vsync = False
Enable Fog = False
Enable Perspective Correction = True
Enable Texture Filter = False
Enable High-Res Textures = False
Enable Framebuffer Emulation = False
Enable Framebuffer Effect = False
Enable Alpha Blending = True
Enable Multi-Sampling = False
Enable Runfast = True
Enable Framerate Counter = False
Enable Wireframe = False
Enable Anisotropic Filtering = 1
Enable Buffer Copy = True

[Video-Enhancements]
Enable Fog = False
Enable Alpha Test = True
Enable Anti-Aliasing = False
Enable Alpha-to-Coverage = False
Enable Texture Sharpening = False
Enable Shader Cache = False

[Audio-General]
Audio Plugin = SDL Audio Plugin
Enable Audio = True
Frequency = 22050
Resample Quality = 2
Buffer Size = 2048

[Input-Default]
Input Plugin = SDL Input Plugin
Analog Stick X = A,D
Analog Stick Y = W,S
C Button Up = I
C Button Down = K
C Button Left = J
C Button Right = L
A Button = Z
B Button = X
Z Button = C
L Button = Q
R Button = E
D-Pad Up = Arrow Up
D-Pad Down = Arrow Down
D-Pad Left = Arrow Left
D-Pad Right = Arrow Right
Start Button = Enter

[Core-Settings]
Use External Memory = True
Enable Cheats = False
Save State Directory = /savestates
